version: '3.8'

services:
  kolam-heritage:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend/instance:/app/backend/instance
      - ./backend/storage:/app/backend/storage
    environment:
      - FLASK_ENV=production
      - FLASK_APP=backend/app.py
    restart: unless-stopped

  kolam-heritage-dev:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=backend/app.py
      - FLASK_DEBUG=1
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
    restart: unless-stopped