services:
  - type: web
    name: ar-bharat-frontend
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: ar-bharat-backend
    runtime: python
    plan: free
    region: oregon  
    branch: main
    rootDir: ./backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend